Flownative:
  Flow:
    ResourceProxy:
      storages: []
#      storages:
#        # the default storage for a Flow setup
#        'defaultPersistentResourcesStorage':
#          # the remote base URI to the published resources
#          remoteSourceBaseUri: 'https://www.acme.com/_Resources/Persistent'
#          # whether or not the remote source uses the target setting of the same name
#          subdivideHashPathSegment: true
